# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import xlutils_view as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    dict_0 = {}
    module_0.SheetView(dict_0, dict_0, col_slice=dict_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -429
    module_0.View(int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.View(none_type_0)


def test_case_3():
    none_type_0 = None
    row_0 = module_0.Row(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    none_type_0 = None
    row_0 = module_0.Row(none_type_0)
    row_0.__index__()


@pytest.mark.xfail(strict=True)
def test_case_5():
    none_type_0 = None
    col_0 = module_0.Col(none_type_0)
    col_0.__index__()
