# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import db_create as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.create_table(none_type_0, none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "^-{W#O\\~e,U"
    module_0.make_sqlalchemy_column(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    module_0.create_table(
        bool_0, bool_0, bool_0, constraints=bool_0, metadata=bool_0, sample=bool_0
    )


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "S2PyH8mnRB^Ir"
    module_0.drop_table(str_0, str_0, commit=str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "Zq-=P7J/d"
    module_0.drop_table(str_0, str_0, str_0)
