# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import gsheet as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.fromgsheet(none_type_0, none_type_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "gsheet.GoogleSheetView"
    )
    assert var_0.auth_info is None
    assert var_0.spreadsheet is None
    assert var_0.worksheet is None
    assert var_0.cell_range is None
    assert var_0.open_by_key is False
