# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import whoosh as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.fromtextindex(none_type_0, none_type_0, none_type_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}" == "whoosh.TextIndexView"
    )
    assert var_0.index_or_dirname is None
    assert var_0.indexname is None
    assert var_0.docnum_field is None


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    var_0 = module_0.fromtextindex(bool_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}" == "whoosh.TextIndexView"
    )
    assert var_0.index_or_dirname is False
    assert var_0.indexname is None
    assert var_0.docnum_field is None
    text_index_view_0 = module_0.TextIndexView(var_0)
    var_0.compress(bool_0)


def test_case_2():
    none_type_0 = None
    var_0 = module_0.searchtextindex(
        none_type_0,
        none_type_0,
        indexname=none_type_0,
        docnum_field=none_type_0,
        score_field=none_type_0,
    )
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "whoosh.SearchTextIndexView"
    )


def test_case_3():
    list_0 = []
    search_text_index_view_0 = module_0.searchtextindexpage(
        list_0, list_0, list_0, list_0, list_0, fieldboosts=list_0
    )
    assert (
        f"{type(search_text_index_view_0).__module__}.{type(search_text_index_view_0).__qualname__}"
        == "whoosh.SearchTextIndexView"
    )


def test_case_4():
    list_0 = []
    iter_container_0 = module_0.SearchTextIndexView(list_0, list_0, score_field=list_0)
    assert (
        f"{type(iter_container_0).__module__}.{type(iter_container_0).__qualname__}"
        == "whoosh.SearchTextIndexView"
    )
    var_0 = iter_container_0.__iter__()
