# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import remotes as module_0
import petl.io.sources as module_1


def test_case_0():
    bool_0 = True
    s_m_b_source_0 = module_0.SMBSource(bool_0)


def test_case_1():
    none_type_0 = None
    remote_source_0 = module_0.RemoteSource(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    remote_source_0 = module_0.RemoteSource(bool_0)
    var_0 = module_1.get_reader(remote_source_0)
    remote_source_1 = module_0.RemoteSource(var_0)
    remote_source_1.open_file()
