# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import pandas as module_0
import inspect as module_1
import collections.abc as module_2


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xf1s="
    module_0.todataframe(bytes_0, exclude=bytes_0, columns=bytes_0)


def test_case_1():
    none_type_0 = None
    with pytest.raises(AssertionError):
        module_0.DataFrameView(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.fromdataframe(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    var_0 = module_1.trace()
    module_0.todataframe(var_0, exclude=var_0, coerce_float=var_0, nrows=var_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    var_0 = module_1.stack()
    module_0.todataframe(var_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    var_0 = module_1._ParameterKind.VAR_KEYWORD
    var_1 = module_2.ValuesView(var_0)
    module_0.todataframe(var_1, coerce_float=var_1, nrows=var_0)
