# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import xlsx as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.toxlsx(none_type_0, none_type_0)


def test_case_1():
    bool_0 = False
    var_0 = module_0.fromxlsx(bool_0)
    assert f"{type(var_0).__module__}.{type(var_0).__qualname__}" == "xlsx.XLSXView"
    assert var_0.filename is False
    assert var_0.sheet is None
    assert var_0.range_string is None
    assert var_0.min_row is None
    assert var_0.min_col is None
    assert var_0.max_row is None
    assert var_0.max_col is None
    assert var_0.read_only is False
    assert var_0.kwargs == {}
