# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import pytables as module_0


def test_case_0():
    bytes_0 = b"_\xb2O\x92\x05W_\x02"
    var_0 = module_0.fromhdf5sorted(bytes_0, sortby=bytes_0, step=bytes_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "pytables.HDF5SortedView"
    )
    assert var_0.source == b"_\xb2O\x92\x05W_\x02"
    assert var_0.where is None
    assert var_0.name is None
    assert var_0.sortby == b"_\xb2O\x92\x05W_\x02"
    assert var_0.checkCSI is False
    assert var_0.start is None
    assert var_0.stop is None
    assert var_0.step == b"_\xb2O\x92\x05W_\x02"


def test_case_1():
    bytes_0 = b"_\xb2O\x92\x05W_\x02"
    with pytest.raises(AssertionError):
        module_0.fromhdf5sorted(bytes_0, name=bytes_0, step=bytes_0)


def test_case_2():
    none_type_0 = None
    var_0 = module_0.iterhdf5sorted(
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
        none_type_0,
    )


def test_case_3():
    none_type_0 = None
    var_0 = module_0.fromhdf5(
        none_type_0,
        name=none_type_0,
        condvars=none_type_0,
        stop=none_type_0,
        step=none_type_0,
    )
    assert f"{type(var_0).__module__}.{type(var_0).__qualname__}" == "pytables.HDF5View"
    assert var_0.source is None
    assert var_0.where is None
    assert var_0.name is None
    assert var_0.condition is None
    assert var_0.condvars is None
    assert var_0.start is None
    assert var_0.stop is None
    assert var_0.step is None


def test_case_4():
    none_type_0 = None
    h_d_f5_view_0 = module_0.HDF5View(none_type_0)
    assert (
        f"{type(h_d_f5_view_0).__module__}.{type(h_d_f5_view_0).__qualname__}"
        == "pytables.HDF5View"
    )
    assert h_d_f5_view_0.source is None
    assert h_d_f5_view_0.where is None
    assert h_d_f5_view_0.name is None
    assert h_d_f5_view_0.condition is None
    assert h_d_f5_view_0.condvars is None
    assert h_d_f5_view_0.start is None
    assert h_d_f5_view_0.stop is None
    assert h_d_f5_view_0.step is None


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = True
    var_0 = module_0.fromhdf5sorted(bool_0, sortby=bool_0, checkCSI=bool_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "pytables.HDF5SortedView"
    )
    assert var_0.source is True
    assert var_0.where is None
    assert var_0.name is None
    assert var_0.sortby is True
    assert var_0.checkCSI is True
    assert var_0.start is None
    assert var_0.stop is None
    assert var_0.step is None
    none_type_0 = None
    var_1 = module_0.fromhdf5(none_type_0, name=none_type_0)
    assert f"{type(var_1).__module__}.{type(var_1).__qualname__}" == "pytables.HDF5View"
    assert var_1.source is None
    assert var_1.where is None
    assert var_1.name is None
    assert var_1.condition is None
    assert var_1.condvars is None
    assert var_1.start is None
    assert var_1.stop is None
    assert var_1.step is None
    var_1.sum()


def test_case_6():
    none_type_0 = None
    h_d_f5_sorted_view_0 = module_0.HDF5SortedView(
        none_type_0, name=none_type_0, step=none_type_0
    )
    assert (
        f"{type(h_d_f5_sorted_view_0).__module__}.{type(h_d_f5_sorted_view_0).__qualname__}"
        == "pytables.HDF5SortedView"
    )
    assert h_d_f5_sorted_view_0.source is None
    assert h_d_f5_sorted_view_0.where is None
    assert h_d_f5_sorted_view_0.name is None
    assert h_d_f5_sorted_view_0.sortby is None
    assert h_d_f5_sorted_view_0.checkCSI is False
    assert h_d_f5_sorted_view_0.start is None
    assert h_d_f5_sorted_view_0.stop is None
    assert h_d_f5_sorted_view_0.step is None


def test_case_7():
    bytes_0 = b"/^1'\x13\x92C\xe0g1\x0fs-w\xdcH\x8a\xe9\xd0\xd8"
    none_type_0 = None
    var_0 = module_0.iterhdf5sorted(
        bytes_0, bytes_0, bytes_0, bytes_0, bytes_0, bytes_0, none_type_0, bytes_0
    )
    list_0 = [bytes_0, bytes_0, bytes_0]
    bool_0 = True
    none_type_1 = None
    h_d_f5_sorted_view_0 = module_0.HDF5SortedView(none_type_0)
    assert (
        f"{type(h_d_f5_sorted_view_0).__module__}.{type(h_d_f5_sorted_view_0).__qualname__}"
        == "pytables.HDF5SortedView"
    )
    assert h_d_f5_sorted_view_0.source is None
    assert h_d_f5_sorted_view_0.where is None
    assert h_d_f5_sorted_view_0.name is None
    assert h_d_f5_sorted_view_0.sortby is None
    assert h_d_f5_sorted_view_0.checkCSI is False
    assert h_d_f5_sorted_view_0.start is None
    assert h_d_f5_sorted_view_0.stop is None
    assert h_d_f5_sorted_view_0.step is None
    var_1 = h_d_f5_sorted_view_0.filter(none_type_0)
    var_2 = module_0.iterhdf5(
        list_0, bytes_0, bytes_0, list_0, bool_0, bytes_0, none_type_1, list_0
    )
    var_3 = var_2.__iter__()
