# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import _multilayer as module_0


def test_case_0():
    multi_layer_0 = module_0._MultiLayer()
