# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mlxtend.preprocessing.mean_centering as module_0
import inspect as module_1


def test_case_0():
    mean_centerer_0 = module_0.MeanCenterer()
    with pytest.raises(AttributeError):
        mean_centerer_0.transform(mean_centerer_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    mean_centerer_0 = module_0.MeanCenterer()
    var_0 = module_1.stack()
    mean_centerer_0.fit_transform(var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    mean_centerer_0 = module_0.MeanCenterer()
    none_type_0 = None
    mean_centerer_0.fit_transform(none_type_0)


def test_case_3():
    mean_centerer_0 = module_0.MeanCenterer()


@pytest.mark.xfail(strict=True)
def test_case_4():
    mean_centerer_0 = module_0.MeanCenterer()
    none_type_0 = None
    var_0 = module_1.getouterframes(none_type_0)
    mean_centerer_0.fit_transform(var_0)
