# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mlxtend.classifier._base_classification as module_0
import sysconfig as module_1


def test_case_0():
    base_stacking_classifier_0 = module_0._BaseStackingClassifier()


@pytest.mark.xfail(strict=True)
def test_case_1():
    base_stacking_classifier_0 = module_0._BaseStackingClassifier()
    none_type_0 = None
    base_stacking_classifier_0.score(none_type_0, base_stacking_classifier_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    list_0 = []
    base_stacking_classifier_0 = module_0._BaseStackingClassifier(*list_0)
    base_stacking_classifier_1 = module_0._BaseStackingClassifier()
    var_0 = module_1.get_platform()
    base_stacking_classifier_1.predict_proba(base_stacking_classifier_1)


@pytest.mark.xfail(strict=True)
def test_case_3():
    base_stacking_classifier_0 = module_0._BaseStackingClassifier()
    base_stacking_classifier_0.decision_function(base_stacking_classifier_0)
