# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mlxtend.file_io.find_filegroups as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xd0\x86\xaa\xa6M\x01k\xe3\xa2\x1fJXA3l;^"
    module_0.find_filegroups(bytes_0)


def test_case_1():
    set_0 = set()
    with pytest.raises(AssertionError):
        module_0.find_filegroups(set_0, ignore_invisible=set_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.find_filegroups(
        none_type_0,
        extensions=none_type_0,
        ignore_invisible=none_type_0,
        rstrip=none_type_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b"\xa1^\xb1?Z\xa1\xfcf\xcb\xccu+"
    module_0.find_filegroups(bytes_0, extensions=bytes_0)


def test_case_4():
    bytes_0 = b"\x04\xa6"
    str_0 = "J<IjnhVN"
    with pytest.raises(AssertionError):
        module_0.find_filegroups(bytes_0, extensions=str_0)
