# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mlxtend.classifier.perceptron as module_0


def test_case_0():
    perceptron_0 = module_0.Perceptron()
    assert (
        f"{type(perceptron_0).__module__}.{type(perceptron_0).__qualname__}"
        == "mlxtend.classifier.perceptron.Perceptron"
    )
    assert perceptron_0.eta == pytest.approx(0.1, abs=0.01, rel=0.01)
    assert perceptron_0.epochs == 50
    assert perceptron_0.random_seed is None
    assert perceptron_0.print_progress == 0
