# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mlxtend.file_io.find_files as module_0


def test_case_0():
    str_0 = "."
    var_0 = module_0.find_files(str_0, str_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.find_files(none_type_0, none_type_0)


def test_case_2():
    str_0 = "TP"
    none_type_0 = None
    var_0 = module_0.find_files(str_0, str_0, str_0, ignore_invisible=none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "t\n]Z%W%9=RnG_{Cv}"
    none_type_0 = None
    var_0 = module_0.find_files(str_0, none_type_0, none_type_0, ignore_substring=str_0)
    module_0.find_files(var_0, var_0)


def test_case_4():
    str_0 = "t\n]Z%W%9=RnG_{Cv}"
    none_type_0 = None
    var_0 = module_0.find_files(
        str_0, none_type_0, check_ext=str_0, ignore_invisible=str_0
    )


def test_case_5():
    str_0 = "TtXu;!K#&Q7'K{("
    none_type_0 = None
    var_0 = module_0.find_files(str_0, none_type_0, ignore_substring=str_0)
    none_type_1 = None
    var_1 = module_0.find_files(
        str_0, none_type_1, check_ext=none_type_1, ignore_invisible=none_type_0
    )


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = "."
    none_type_0 = None
    var_0 = module_0.find_files(str_0, none_type_0, ignore_substring=str_0)
    none_type_1 = None
    module_0.find_files(str_0, none_type_1, check_ext=str_0, ignore_invisible=str_0)


def test_case_7():
    str_0 = "."
    var_0 = module_0.find_files(str_0, str_0, check_ext=str_0, ignore_invisible=str_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    str_0 = "."
    none_type_0 = None
    var_0 = module_0.find_files(str_0, str_0, ignore_invisible=none_type_0)
    var_1 = module_0.find_files(str_0, str_0, check_ext=str_0, ignore_invisible=str_0)
    var_2 = module_0.find_files(str_0, str_0, str_0, ignore_invisible=var_1)
    module_0.find_files(var_1, var_1, check_ext=var_1)
