# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import _cluster as module_0


def test_case_0():
    cluster_0 = module_0._Cluster()
