# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import _iterative_model as module_0


def test_case_0():
    iterative_model_0 = module_0._IterativeModel()
